version: '3'
services:
  app:
    image: miniapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_CONN_STRING="mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.10.6"
      - PORT="3000"
      - DB_NAME="miniapi"
      - POSTS_COLLECTION_NAME="posts"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
